# Generated by Django 3.2.15 on 2022-09-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('pipeline_type', models.CharField(choices=[('I', 'Import'), ('R', 'Reimport')], default='I', max_length=1)),
                ('pipeline_config', models.JSONField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=32, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
