# Generated by Django 3.2.15 on 2022-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(default=435345345, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('S', 'Success'), ('F', 'Failure')], default='R', max_length=1),
        ),
    ]
