# Generated by Django 3.2.15 on 2022-09-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_auto_20220923_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.TextField(max_length=10000)),
                ('name', models.CharField(max_length=255)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('pipeline_config', models.JSONField()),
                ('pipeline_type', models.CharField(choices=[('I', 'Import'), ('R', 'Reimport')], default='I', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pipeline_config',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pipeline_type',
        ),
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipelines.batchtask'),
        ),
    ]
