# Generated by Django 3.2.15 on 2022-10-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_auto_20220926_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='input',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pipelines.batchtask'),
        ),
    ]
