# Generated by Django 3.2.15 on 2022-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_task_pipeline_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtask',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
