# Generated by Django 3.2.15 on 2022-12-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_alter_task_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pipeline_config',
        ),
    ]
