# Generated by Django 3.2.15 on 2023-05-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_remove_task_pipeline_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('S', 'Success'), ('F', 'Failure'), ('ST', 'Stopped')], default='R', max_length=2),
        ),
    ]
